version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: glider911
      MYSQL_INITDB_SKIP_TZINFO: '1'
      MYSQL_DATABASE: finanzas
      MYSQL_USER: admin
      MYSQL_PASSWORD: adminpassword
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'  # Permitir conexiones sin contraseña
    ports:
      - 3306:3306
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database.py:/app/database.py  # Montar el archivo database.py como volumen
    networks:
      - mynetwork

  zabbix-agent:
    image: zabbix/zabbix-agent2
    restart: always
    environment:
      - ZBX_SERVER_HOST: 192.168.20.50
      - ZBX_SERVER_PORT: 1050
    networks:
      - mynetwork

networks:
  mynetwork:
